				<li>
					<label for="<?php echo $field; ?>"><?php echo ucfirst($field); ?></label><input type="text" name="<?php echo $field; ?>" value="" id="<?php echo $field; ?>" />
					<span class="tool"><a href="#" onclick="d=new Date(); ds=d.toString(); ds=ds.split(' '); v=ds[1]+' '+ds[2]+', '+ds[3]; document.getElementById('<?php echo $field; ?>').value=v;return false;">Insert Current Date</a></span>
				</li>
