		<h1>Edit :hname_object: :php_echo $this->:object;:php_close</h1>
		<form enctype="multipart/form-data" action=":php_echo '/:object/update/'.params("id");:php_close" method="post">
			:php_open render_partial('form', $this->:object); :php_close
			
			<div id="footer">
				:php_echo submit_to('Edit');:php_close
				:php_echo button_to('Cancel', '/'.params('controller').'/show/'.$this->:object->id);:php_close
			</div>
		</form>
