:php_echo xml_declaration(); :php_close
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>:php_echo ucwords(to_human_name(params('controller'))); :php_close: :php_echo ucwords(to_human_name(params('action'))); :php_close</title>
		:php_echo stylesheet_link_tag('scaffold'); :php_close
	</head>

	<body>
		<?php echo $content_for_layout;?>
	</body>
</html>
