:php_echo xml_declaration(); :php_close
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>:php_echo ucfirst(params('controller'));:php_close: index</title>
  	<link href="/_css/scaffold.css" media="screen" rel="Stylesheet" type="text/css" />
	</head>

	<body>
		<h1>Listing :php_echo ucfirst(params('controller'));:php_close</h1>
		
		<ul id="listing">
			:php_open $alt = 0;	:php_close
			:php_open foreach ($:objects as $:object): :php_close
			
				<li class="row:php_echo $alt; :php_close">
					<span class="controls">
						:php_echo link_to("Edit", array('action'=>'edit', 'uid'=>$:object->uid));:php_close |
						:php_echo link_to("Delete", array('action'=>'delete', 'uid'=>$:object->uid), true);:php_close
					</span>
					:php_echo link_to($:object, array('action'=>'show', 'uid'=>$:object->uid));:php_close
				</li>
			:php_open $alt = 1 - $alt;	:php_close
			:php_open endforeach :php_close
		</ul>
		
		<div id="footer">
			:php_echo link_to('New '.ucfirst(params('controller')), array('action'=>'new'));:php_close
		</div>

	</body>
</html>
