:php_echo xml_declaration(); :php_close
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Create :php_echo ucfirst(params("controller"));:php_close</title>
  	<link href="/_css/scaffold.css" media="screen" rel="Stylesheet" type="text/css" />
	</head>

	<body>
		<h1>Create :php_echo ucfirst(params("controller"));:php_close</h1>
		<form action=":php_echo url_for(array('action'=>'create'));:php_close" method="post">
			:php_open render_partial(false, 'form', $:object); :php_close

			<div id="footer">
				:php_echo submit_to('Create');:php_close
				:php_echo button_to('Cancel', false);:php_close
			</div>
		</form>
	</body>
</html>
