		<h1>Show :hname_object: :php_echo $this->:object; :php_close</h1>
		<dl>
			:php_open foreach ($this->:object as $k=>$v): :php_close
				<dt><strong>:php_echo str_replace('_', ' ', ucfirst($k)); :php_close</strong>:</dt>
				<dd>:php_echo $v; :php_close</dd>
			:php_open endforeach :php_close
		</dl>
		
		<div id="footer">
			:php_echo link_to('Back', false);:php_close | 
			:php_echo link_to('Edit', array('action'=>'edit', 'uid'=>$this->:object->uid));:php_close
		</div>
