<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Show <?php echo ucfirst(params('controller')); ?>: <?php echo $:object; ?></title>
  	<link href="/_css/scaffold.css" media="screen" rel="Stylesheet" type="text/css" />
	</head>

	<body>
		<h1>Show <?php echo ucfirst(params('controller')); ?>: <?php echo $:object; ?></h1>
		<dl>
			<?php foreach ($:object as $k=>$v): ?>
				<dt><strong><?php echo str_replace('_', ' ', ucfirst($k)); ?></strong>:</dt>
				<dd><?php echo $v; ?></dd>
			<?php endforeach ?>
		</dl>
		
		<div id="footer">
			<?php echo link_to('Back', false);?> | 
			<?php echo link_to('Edit', array('action'=>'edit', 'uid'=>$:object->uid));?>
		</div>
	</body>
</html>
