<li>
	<label for="<?php echo $field; ?>"><?php echo ucfirst($field); ?></label><input type="text" name="<?php echo $field; ?>" value="" id="<?php echo $field; ?>" />
	<span class="tool"><a href="#" onclick="d=new Date(); ds=d.toString(); ds=ds.split(' '); v=ds[4].substring(0,ds[4].lastIndexOf(':'))+(d.getHours()>11?' PM':' AM'); document.getElementById('<?php echo $field; ?>').value=v;return false;">Insert Current Time</a></span>
</li>
