#!/usr/bin/php

<?php
	define('SAINT_ROOT', array_key_exists('SAINT_ROOT', $_SERVER)?$_SERVER['SAINT_ROOT']:'/Users/chandler/Projects/Saint/saint/saint');

	if(!defined('SAINT_ROOT')) {
	
		# first use the version in lib, then check and env var, then just blindly try.
		$s = realpath(dirname(__FILE__).'/../lib/saint');
		if ($s !== false) {
			define('SAINT_ROOT', $s);
		} else if (array_key_exists('SAINT_ROOT', $_SERVER)) {
			define('SAINT_ROOT', $_SERVER['SAINT_ROOT']);
		}
	}
	include SAINT_ROOT."/scripts/generate";

?>
