<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title><?php echo $type; ?> Error</title>
		<meta HTTP-EQUIV="Pragma" content="no-cache" />
		<meta HTTP-EQUIV="Cache-Control" content="no-cache" />

		<style type="text/css">
			* { font-family: Trebuchet MS, arial, helvetica, sans-serif; color: #282220;}
			body { background-color: #fff; margin: 0px; }
			h1 { background-color: #fdfdfd; color: #F04F2D; margin-top: 0px; margin-bottom: 0px; padding: 10px; border-top: 10px solid #282220; border-bottom: 1px solid #282220; height: 70px; }
			h2 { background-color: #fdfdfd; color: #282220; border-bottom: 1px solid #282220; font-size:14px; margin: 40px 0px 0px 0px; padding-left: 10px;}
			p, li { background-color: #eee; margin-top: 0px; padding: 10px; font-size: 12px; }
			li { margin-bottom: 2px; padding: 0px; }
			ul { background-color: #eee; list-style: none; padding: 10px 0px 0px 10px; margin: 0px;}
		</style>
	</head>

	<body>
		<h1><?php echo $type; ?> Error</h1>
		
		<p>
			<b><?php echo $msg; ?></b><br /><br />
			Occurred in <b><?php echo str_replace(PROJECT_ROOT.'/', '', $file); ?></b> on line <b><?php echo $line; ?></b>.
		</p>

		<h2>Trace</h2>
		<ul>
			<?php echo $trace; ?>
		</ul>

		<h2>Request</h2>
		<p><?php var_export(params()); ?></p>
	</body>
</html>

