<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Exception caught</title>

		<style type="text/css">
			* { font-family: Trebuchet MS, arial, helvetica, sans-serif; color: #282220;}
			body { background-color: #fff; margin: 0px; }
			h1 { background-color: #fdfdfd; color: #1EB136; margin-top: 0px; margin-bottom: 0px; padding: 10px; border-top: 10px solid #282220; border-bottom: 1px solid #282220; height: 70px; }
			p, li { background-color: #eee; margin-top: 0px; padding: 10px; font-size: 11px; }
			li { margin-bottom: 2px; padding: 0px 0px 0px 10px; }
			ul { background-color: #eee; list-style: none; padding: 0px; margin: 0px;}
		</style>
	</head>

	<body>
		<h1>Error</h1>
		
		<p><?php echo $msg; ?></p>
		<ul>
			<?php echo $trace; ?>
		</ul>
	</body>
</html>

