#!/usr/bin/php
<?php

	define ('SAINT_ROOT', realpath(dirname(__FILE__).'/..'));
	
	# define some locations
	define ('SAINT_APP_TEMPLATE', SAINT_ROOT.'/templates/application');
	
	#get some useful shell funcs
	require_once (SAINT_ROOT."/scripts/shell_lib");

	
	
	# grab out the args and create the application
	if (!array_key_exists(1, $_SERVER['argv'])) {
		error("Please specify an application name.", true)
	}
	$argv = $_SERVER['argv'][1];
	
	# make dir
	$dir = safe_mkdir($argv);
	
	# copy application
	copyr(SAINT_APP_TEMPLATE, $dir);
	
	# set perms on scripts
	chmodr("$dir/scripts", "0777");
	
	# set saint root in scripts
	$scripts = get_files("$dir/scripts");
	foreach($scripts as $k => $v) {
		$s = file_get_contents("$dir/scripts/$v");
		$s = str_replace("<?php\n", "<?php\n	define('SAINT_ROOT', '".SAINT_ROOT."');\n", $s);
		
		$f = fopen("$dir/scripts/$v", 'w');
		fwrite($f, $s);
		fclose($f);
	}


	
?>